### ISSUE TITLE
import zmq

### ISSUE THREAD

**Issue by Prj1508** [commaai/openpilot-tools#22]
I am installing openpilot tools and I have followed the process as per https://github.com/commaai/openpilot-tools

When I run joystickd.py (python carcontrols/joystickd.py). I am getting this error message 

~/comma/openpilot/tools$  python carcontrols/joystickd.py
Traceback (most recent call last):
  File "carcontrols/joystickd.py", line 10, in <module>
    import zmq
ImportError: No module named zmq

Please help to resolve this

**Comment by Prj1508** [comment]
I installed zmq module again (besides the process outlined), and now its complaining
 Traceback (most recent call last):
  File "carcontrols/joystickd.py", line 11, in <module>
    from selfdrive.services import service_list
ImportError: No module named selfdrive.services

**Comment by pd0wm** [comment]
Did you checkout the tools repository inside of openpilot (step 3 & 4 of the installation instructions)?

**Comment by Prj1508** [comment]
Yes. To make sure I tried to enter shell and it says:
pipenv shell
Shell for /home/jpm/.local/share/virtualenvs/openpilot-a2eC1UfR already activated.
No action taken to avoid nested environments.

Now, I am getting this error message when i run joystickd.py

~/comma/openpilot/tools$ python carcontrols/joystickd.py
Traceback (most recent call last):
  File "carcontrols/joystickd.py", line 9, in <module>
    import pygame
ImportError: No module named pygame

**Comment by pd0wm** [comment]
Ah, that package is in the dev dependencies. Can you also install the development dependencies using `pipenv install --dev`? If that works I'll update the readme.

**Comment by Prj1508** [comment]
I tried to install dev dependencies and here is the error log

pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/cli/command.py", line 254, in install
[pipenv.exceptions.InstallError]:       editable_packages=state.installstate.editables,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1874, in do_install
[pipenv.exceptions.InstallError]:       keep_outdated=keep_outdated
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 862, in do_install_dependencies
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, False, failed_deps_queue, retry=False)
[pipenv.exceptions.InstallError]:   File "/usr/local/lib/python2.7/dist-packages/pipenv/core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting pycurl==7.43.0.3 (from -r /tmp/pipenv-rJbMQD-requirements/pipenv-YMGina-requirement.txt (line 1))', '  Using cached https://files.pythonhosted.org/packages/ac/b3/0f3979633b7890bab6098d84c84467030b807a1e2b31f5d30103af5a71ca/pycurl-7.43.0.3.tar.gz', 'Building wheels for collected packages: pycurl', '  Building wheel for pycurl (setup.py): started', "  Building wheel for pycurl (setup.py): finished with status 'error'", '  Running setup.py clean for pycurl', 'Failed to build pycurl', 'Installing collected packages: pycurl', '  Running setup.py install for pycurl: started', "    Running setup.py install for pycurl: finished with status 'error'"]
[pipenv.exceptions.InstallError]: ["DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support", '  ERROR: Command errored out with exit status 1:', '   command: /home/jpm/.local/share/virtualenvs/openpilot-b74-wh9x/bin/python2.7 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-3xImMQ/pycurl/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-3xImMQ/pycurl/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' bdist_wheel -d /tmp/pip-wheel-vvNySh --python-tag cp27', '       cwd: /tmp/pip-install-3xImMQ/pycurl/', '  Complete output (20 lines):', '  Using curl-config (libcurl 7.47.0)', '  Using SSL library: GnuTLS', '  running bdist_wheel', '  running build', '  running build_py', '  creating build', '  creating build/lib.linux-x86_64-2.7', '  creating build/lib.linux-x86_64-2.7/curl', '  copying python/curl/__init__.py -> build/lib.linux-x86_64-2.7/curl', '  warning: build_py: byte-compiling is disabled, skipping.', '  ', '  running build_ext', "  building 'pycurl' extension", '  creating build/temp.linux-x86_64-2.7', '  creating build/temp.linux-x86_64-2.7/src', '  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYCURL_VERSION="7.43.0.3" -DHAVE_CURL_SSL=1 -DHAVE_CURL_GNUTLS=1 -DHAVE_CURL_SSL=1 -I/usr/include/python2.7 -c src/docstrings.c -o build/temp.linux-x86_64-2.7/src/docstrings.o', '  In file included from src/docstrings.c:4:0:', '  src/pycurl.h:168:30: fatal error: gnutls/gnutls.h: No such file or directory', '  compilation terminated.', "  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1", '  ----------------------------------------', '  ERROR: Failed building wheel for pycurl', '    ERROR: Command errored out with exit status 1:', '     command: /home/jpm/.local/share/virtualenvs/openpilot-b74-wh9x/bin/python2.7 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-3xImMQ/pycurl/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-3xImMQ/pycurl/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-04ZwX4/install-record.txt --single-version-externally-managed --compile --install-headers /home/jpm/.local/share/virtualenvs/openpilot-b74-wh9x/include/site/python2.7/pycurl', '         cwd: /tmp/pip-install-3xImMQ/pycurl/', '    Complete output (20 lines):', '    Using curl-config (libcurl 7.47.0)', '    Using SSL library: GnuTLS', '    running install', '    running build', '    running build_py', '    creating build', '    creating build/lib.linux-x86_64-2.7', '    creating build/lib.linux-x86_64-2.7/curl', '    copying python/curl/__init__.py -> build/lib.linux-x86_64-2.7/curl', '    warning: build_py: byte-compiling is disabled, skipping.', '    ', '    running build_ext', "    building 'pycurl' extension", '    creating build/temp.linux-x86_64-2.7', '    creating build/temp.linux-x86_64-2.7/src', '    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DPYCURL_VERSION="7.43.0.3" -DHAVE_CURL_SSL=1 -DHAVE_CURL_GNUTLS=1 -DHAVE_CURL_SSL=1 -I/usr/include/python2.7 -c src/docstrings.c -o build/temp.linux-x86_64-2.7/src/docstrings.o', '    In file included from src/docstrings.c:4:0:', '    src/pycurl.h:168:30: fatal error: gnutls/gnutls.h: No such file or directory', '    compilation terminated.', "    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1", '    ----------------------------------------', 'ERROR: Command errored out with exit status 1: /home/jpm/.local/share/virtualenvs/openpilot-b74-wh9x/bin/python2.7 -u -c \'import sys, setuptools, tokenize; sys.argv[0] = \'"\'"\'/tmp/pip-install-3xImMQ/pycurl/setup.py\'"\'"\'; __file__=\'"\'"\'/tmp/pip-install-3xImMQ/pycurl/setup.py\'"\'"\';f=getattr(tokenize, \'"\'"\'open\'"\'"\', open)(__file__);code=f.read().replace(\'"\'"\'\\r\\n\'"\'"\', \'"\'"\'\\n\'"\'"\');f.close();exec(compile(code, __file__, \'"\'"\'exec\'"\'"\'))\' install --record /tmp/pip-record-04ZwX4/install-record.txt --single-version-externally-managed --compile --install-headers /home/jpm/.local/share/virtualenvs/openpilot-b74-wh9x/include/site/python2.7/pycurl Check the logs for full command output.']
ERROR: ERROR: Package installation failed...

I continue to get the "ImportError: No module named pygame: when I run joystickd.py

**Comment by pd0wm** [comment]
Thanks for checking it! If I have some time I'll add the needed dependencies to the instructions.

For now you can just do `pipenv install pygame`, and that error will go away.

**Comment by Prj1508** [comment]
I tried pipenv install pygame, but the error still remains. Its not installing all the dev dependencies

**Comment by pd0wm** [comment]
I updated the instructions for the correct procedure.

1) `pipenv install` from the openpilot directory (without --dev)
2) `pipenv shell` to activate the env
3) `pip install -r requirements.txt` from openpilot/tools to install the rest of the requirements

**Comment by Prj1508** [comment]
I followed this instructions and I am getting below error
(openpilot) test@tester:~/comma/zeromq-4.2.3/c-capnproto/openpilot/tools$ python carcontrols/joystickd.py
Traceback (most recent call last):
  File "carcontrols/joystickd.py", line 11, in <module>
    from selfdrive.services import service_list
ImportError: No module named selfdrive.services

It also complaigned " ERROR: pycocotools 2.0 has requirement matplotlib>=2.1.0, but you'll have matplotlib 2.0.2 which is incompatible" when I was installing thru step-3

**Comment by pd0wm** [comment]
Sounds like you need to setup your pythonpath, step 5 of the readme.

**Comment by Prj1508** [comment]
I did set up the path again, but the error message is same as earlier. 

~/comma/zeromq-4.2.3/c-capnproto/openpilot/tools$ python carcontrols/joystickd.py
Traceback (most recent call last):
  File "carcontrols/joystickd.py", line 11, in <module>
    from selfdrive.services import service_list
ImportError: No module named selfdrive.services

**Comment by Prj1508** [comment]
I would like to know if I can bypass this joystick based steering control and just send the values manually from my laptop to panda. This would be even better for me. Please let me know
