### ISSUE TITLE
model_path.poly no member despite using latest openpilot

### ISSUE THREAD

**Issue by arslansarp** [commaai/openpilot-tools#23]
I tried latest openpilot but it gives exactly the same error.

python tools/replay/ui.py 
/home/ipek/openpilot/selfdrive/services.py:13: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  for k, v in yaml.load(f).items():
make: 'simple_kalman_impl.so' is up to date.
mkdir -p obj
ECU Camera Simulated: True
ECU DSU Simulated: True
ECU APGS Simulated: False
ECU Gas Interceptor: False
Traceback (most recent call last):
  File "tools/replay/ui.py", line 584, in <module>
    ui_thread(args.ip_address, args.frame_address)
  File "tools/replay/ui.py", line 416, in ui_thread
    model_data = extract_model_data(md)
  File "tools/replay/ui.py", line 104, in extract_model_data
    cpath=ModelPoly(md.model.path),
  File "tools/replay/ui.py", line 92, in __init__
    if len(model_path.poly):
  File "capnp/lib/capnp.pyx", line 1048, in capnp.lib.capnp._DynamicStructReader.__getattr__
  File "capnp/lib/capnp.pyx", line 1046, in capnp.lib.capnp._DynamicStructReader.__getattr__
  File "capnp/lib/capnp.pyx", line 1042, in capnp.lib.capnp._DynamicStructReader._get
AttributeError: capnp/schema.c++:486: **failed: struct has no such member; name = poly**
stack: 0x7fc70a229718 0x7fc70a03942b 0x7fc70a00f3a6 0x4bc2f8 0x4b9b66 0x4d5669 0x4eef5e 0x4eeb66 0x4aaafb 0x4c166d 0x4c141f 0x4c141f 0x4b9b66 0x4eb69f 0x4e58f2 0x4e41a6 0x4938ce 0x7fc731c68830 0x493299
    ??:0: returning here
    ??:0: returning here
    ??:0: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:?: returning here
    ??:0: returning here

**Comment by pd0wm** [comment]
Oh, I understand what is going on. You're replaying a drive from before the 0.6 update. I'll add some fallback to the ui if the polynomials are not there.

**Comment by pd0wm** [comment]
Turns out the fallback was already in the ui. What drive are you trying to replay? Maybe I can reproduce it.

**Comment by arslansarp** [comment]
Thank you for your response. I was using comma2k19 Dataset.
