### ISSUE TITLE
MOCK=1 tools/replay/boardd.py error

### ISSUE THREAD

**Issue by xx979xx** [commaai/openpilot-tools#36]
(openpilot) xx979xx@xx979xx-Lenovo:~/openpilot$ MOCK=1 tools/replay/boardd.py
attempting can init
got handle
can init done
Traceback (most recent call last):
  File "tools/replay/boardd.py", line 238, in <module>
    main()
  File "tools/replay/boardd.py", line 229, in main
    boardd_mock_loop()
  File "tools/replay/boardd.py", line 130, in boardd_mock_loop
    can_send_many(snd)
  File "tools/replay/boardd.py", line 76, in can_send_many
    snd = snd.ljust(0x10, "\x00")
TypeError: ljust() argument 2 must be a byte string of length 1, not str

**Comment by rbiasini** [comment]
yeah, this script should be deleted. You should use the one in openpilot:
https://github.com/commaai/openpilot/blob/devel/selfdrive/boardd/tests/boardd_old.py

**Comment by xx979xx** [comment]
yes it is working
thanks
