### ISSUE TITLE
Could not find segments for route 99c94dc769b5d96e|2018-11-20--11-58-46 in data directory

### ISSUE THREAD

**Issue by skyphone** [commaai/openpilot-tools#44]
(openpilot) root@chen:/home/chen/openpilot/tools# replay/unlogger.py '99c94dc769b5d96e_2018-11-20--11-58-46--1' /home/chen/logdata/
make: Nothing to be done for 'all'.
keyboard waiting for input
Process Process-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "replay/unlogger.py", line 71, in run
    route = self._process_commands(cmd, route)
  File "replay/unlogger.py", line 128, in _process_commands
    route = Route(cmd.name, cmd.data_dir)
  File "/home/chen/openpilot/tools/lib/route.py", line 15, in __init__
    self._segments = self._get_segments(data_dir)
  File "/home/chen/openpilot/tools/lib/route.py", line 73, in _get_segments
    raise ValueError('Could not find segments for route {} in data directory {}'.format(self.route_name, data_dir))
ValueError: Could not find segments for route 99c94dc769b5d96e|2018-11-20--11-58-46--1 in data directory /home/chen/logdata/

**Comment by skyphone** [comment]
my folder name '99c94dc769b5d96e_2018-11-20--11-58-46--1'  has file fcamera.hevc and rlog.bz2

**Comment by xx979xx** [comment]
check this   #42
it may help
